/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.busyqa.course;

import org.junit.Test;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    }
}
